/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 rsrc/wolfie.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/wolfie.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 2, 0]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone018} />
          <group name="Wolfie">
            <skinnedMesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.Shoe} skeleton={nodes.Cube013.skeleton} />
            <skinnedMesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials.Cap} skeleton={nodes.Cube013_1.skeleton} />
            <skinnedMesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={materials.Head} skeleton={nodes.Cube013_2.skeleton} />
            <skinnedMesh name="Cube013_3" geometry={nodes.Cube013_3.geometry} material={materials.Body} skeleton={nodes.Cube013_3.skeleton} />
            <skinnedMesh name="Cube013_4" geometry={nodes.Cube013_4.geometry} material={materials.Hands} skeleton={nodes.Cube013_4.skeleton} />
            <skinnedMesh name="Cube013_5" geometry={nodes.Cube013_5.geometry} material={materials.Legs} skeleton={nodes.Cube013_5.skeleton} />
            <skinnedMesh name="Cube013_6" geometry={nodes.Cube013_6.geometry} material={materials.Tail} skeleton={nodes.Cube013_6.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wolfie.glb')
